[package]
name = "wbbl"
version = "0.1.0"
authors = ["ncthbrt"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
wee_alloc = ["dep:wee_alloc"]
default = ["console_error_panic_hook", "wee_alloc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = { version = "0.2.91" }
naga = { version = "0.19.2", features = ["wgsl-out"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
glam = "0.25.0"

web-sys = { version = "0.3", features = ["CanvasRenderingContext2d"] }
wee_alloc = { version = "0.4.5", optional = true }


[dev-dependencies]
wasm-bindgen-test = "0.3.41"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
