pub const GEOMETRY_GROUP: u32 = 0;
pub const VERTICES_BINDING: u32 = 0;
pub const INDICES_BINDING: u32 = 1;

pub const FRAME_GROUP: u32 = 1;
pub const FRAME_BINDING: u32 = 0;
pub const MODEL_TRANSFORM_BINDING: u32 = 1;

pub const ARGUMENTS_GROUP: u32 = 2;

pub const PER_SHADER_INPUT_OUTPUT_GROUP: u32 = 3;
pub const COMPUTE_TEXTURE_OUTPUT_BINDING: u32 = 0;
pub const TRIANGLE_INDEX_BUFFER_ARGUMENT_BINDING: u32 = 1;

pub const TEX_COORDINATE_VERTEX_SHADER_INDEX: u32 = 0;
pub const NORMAL_VERTEX_SHADER_INDEX: u32 = 1;
pub const TANGENT_VERTEX_SHADER_INDEX: u32 = 2;
pub const BITANGENT_VERTEX_SHADER_INDEX: u32 = 3;
