pub const GEOMETRY_GROUP: u32 = 0;
pub const VERTICES_BINDING: u32 = 0;
pub const INDICES_BINDING: u32 = 1;

pub const FRAME_DATA_GROUP: u32 = 1;
pub const FRAME_DATA_BINDING: u32 = 0;

pub const ARGUMENTS_GROUP: u32 = 2;

pub const PER_SHADER_INPUT_OUTPUT_GROUP: u32 = 3;
pub const COMPUTE_TEXTURE_OUTPUT_BINDING: u32 = 0;
pub const TRIANGLE_INDEX_BUFFER_ARGUMENT_BINDING: u32 = 1;
