name: Build Web Assembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Wasm Pack
      run: npm install -g wasm-pack
    - name: Install NPM Dependencies
      run: npm ci
    - name: Build WebApp WASM module
      run: wasm-pack build
    - name: Build Appication
      run: npm run build
