name: Build Web Assembly

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install Wasm Pack
        run: npm install -g wasm-pack
      - name: Install NPM Dependencies
        run: npm ci
      - name: Build WebApp WASM module
        run: wasm-pack build
      - name: Build WebApp
        run: npm run build
      - name: Rename Dist Folder
        run: mv ./dist ./app
      - name: Copy WebApp to pages-deployment Branch
        env:
          SRC_FOLDER_PATH: "./app"
          TARGET_BRANCH: "pages-deployment"
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git stash push --all -- $SRC_FOLDER_PATH
          git checkout $TARGET_BRANCH       # checkout to your branch
          git merge --allow-unrelated-histories --squash --strategy-option=theirs stash
          git push origin $TARGET_BRANCH # push to remote branch
