/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AppIndexLazyImport = createFileRoute('/app/')()
const AppTestLazyImport = createFileRoute('/app/test')()

// Create/Update Routes

const AppIndexLazyRoute = AppIndexLazyImport.update({
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route))

const AppTestLazyRoute = AppTestLazyImport.update({
  path: '/app/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app/test.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/test': {
      id: '/app/test'
      path: '/app/test'
      fullPath: '/app/test'
      preLoaderRoute: typeof AppTestLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AppTestLazyRoute,
  AppIndexLazyRoute,
})

/* prettier-ignore-end */
